#!/usr/bin/env bash
# Set the file path
file_path="/etc/passwd"

# Use a while loop to read and process the file line by line
while IFS=: read -r username password uid gid user_info home shell; do
  # Extract user information and format the output
  echo "The user $username is part of the group $gid gang,"
  echo "lives in $home and rides $shell."
  echo "User ID's place is protected by the passcode $password,"
  echo "more info about the user here: $uid $user_info"
  echo
done < "$file_path"
