#!/usr/bin/env bash
# Initialize a counter
count=0

# Use a while loop to display "Best School" 10 times
while [ $count -lt 10 ]
do
  if [ $count -eq 8 ]
  then
    # Display "Best School" on one line and "Hi" on the next line for the 9th iteration
    echo "Best School"
    echo "Hi"
  else
    # Display "Best School" for all other iterations
    echo "Best School"
  fi

  ((count++))
done
