#!/usr/bin/env bash
# Initialize variables for hours and minutes
hour=0
minute=1

# Use a while loop to display the time
while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  while [ $minute -le 59 ]
  do
    echo $minute
    ((minute++))
  done

  # Reset minute and increment hour
  minute=1
  ((hour++))
done
